### ISSUE TITLE
Add Plans to each CourseSelection

### ISSUE THREAD

**Issue by infinitecold** [gzcharleszhang/course-planner#19]
Each CourseSelection needs a slice of Plans that the user intends to complete.

**Comment by gzcharleszhang** [comment]
true

**Comment by infinitecold** [comment]
to do this i ended up moving courseSelections and termSelections (also separated them into 2 files) into a new package to avoid circular dependencies, mb for the huge PR

**Comment by gzcharleszhang** [comment]
solved in #21
