### ISSUE TITLE
Add range-based course requirement

### ISSUE THREAD

**Issue by infinitecold** [gzcharleszhang/course-planner#46]
Needs to be able to handle requirements like

> Three additional CS courses chosen from CS 340-CS 398, CS 440-CS 489.

If in the future we have to deal with requirements that are more complicated, we can consider switching to a regex-based requirement (which all course requirements, including the ones we already have, would be able to follow).

**Comment by gzcharleszhang** [comment]
Any new course requirement type should implement the `CourseRequirementRule` interface, so we can have a `CourseRequirementRange` or `CourseRequirementRegex` that implements that interface, so we can keep all the existing logic we have.
