### ISSUE TITLE
Implement a FromJson function

### ISSUE THREAD

**Issue by infinitecold** [gzcharleszhang/course-planner#56]
We have function that maps an interface -> JSON string (`ToJSON` in `utils.go`), we need its inverse function that maps JSON string -> interface.

**Comment by gzcharleszhang** [comment]
Can u take a look at userHandlers.go and see if it’s something similar? You can construct a struct from a json if u put json tags in the fields.

**Comment by infinitecold** [comment]
I think it's the same, we just should prob abstract it away and put it in `utils.go` since a lot of other places are gonna do the same thing.

**Comment by gzcharleszhang** [comment]
Don’t think there’s a need tho, it’s just one line (the Decode function)
