### ISSUE TITLE
Course Prereqs change

### ISSUE THREAD

**Issue by infinitecold** [gzcharleszhang/course-planner#57]
Same as #53, change from CourseRequirementRule to CourseRequirementRules.

**Comment by infinitecold** [comment]
This would be good to give to @voxelpushing I think

**Comment by gzcharleszhang** [comment]
@voxelpushing finish by midnight ty

**Comment by gzcharleszhang** [comment]
@infinitecold @voxelpushing i'll take over, i'm bored in econ
