### ISSUE TITLE
Use Waterloo API to get course information

### ISSUE THREAD

**Issue by infinitecold** [gzcharleszhang/course-planner#6]

**Comment by gzcharleszhang** [comment]
@infinitecold gonna give kevin this thing

**Comment by voxelpushing** [comment]
gonna work on this in the next few days once i figure out what's going on

**Comment by gzcharleszhang** [comment]
I suggest you to make a separate app that pulls data from the waterloo API, then calls one of `course-planner`'s API endpoint to add the courses and stuff

**Comment by gzcharleszhang** [comment]
you can refactor the directory so then we have like `internal/apps/course-planner/...` and `internal/apps/waterloo-api-caller/...` you can name it w.e u want

**Comment by infinitecold** [comment]
We've decided to version control our data within this repo. This means that this task can be done by a script (doesn't have to be in golang) and the data dumped as JSONs in the `data/` folder. Then, #16 creates a "connector" to put the data from #3 and this ticket into mongo (by calling our REST endpoint).

cc @gzcharleszhang
