### ISSUE TITLE
Plan has CAV requirements

### ISSUE THREAD

**Issue by gzcharleszhang** [gzcharleszhang/course-planner#62]

**Comment by infinitecold** [comment]
I think this can just be a field in Degree that's by default set to 0.

**Comment by gzcharleszhang** [comment]
Yeah that's probably a good idea

**Comment by gzcharleszhang** [comment]
going to add `CAVRequirement` as a concrete implementation of `CourseRequirement`, also planning to rename `CourseRequirement` to just `Requirement`
